#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10
#define HARDIKHYPERIONOS_TOTAL_INTERRUPTS 512

// 100 MB Heap Size
#define HARDIKHYPERIONOS_HEAP_SIZE_BYTES 104857600
#define HARDIKHYPERIONOS_HEAP_BLOCK_SIZE 4096 // 4 KB
#define HARDIKHYPERIONOS_HEAP_ADDRESS 0x01000000
#define HARDIKHYPERIONOS_HEAP_TABLE_ADDRESS 0X00007E00

#define HARDIKHYPERIONOS_SECTOR_SIZE 512

#define HARDIKHYPERIONOS_MAX_FILESYSTEMS 12
#define HARDIKHYPERIONOS_MAX_FILE_DESCRIPTORS 512

#define HARDIKHYPERIONOS_MAX_PATH 108

#endif